replicaCount: 1

image:
  repository: 594081136085.dkr.ecr.eu-north-1.amazonaws.com/golang
  pullPolicy: IfNotPresent
  tag: "0.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  # Supposing we could not modify the application source code
  # Necessary due to an issue between kubernetes and containerd
  # https://github.com/kubernetes/kubernetes/issues/56374
  # https://github.com/containerd/containerd/issues/2516
  sysctls:
  - name: net.ipv4.ip_unprivileged_port_start
    value: "80"

securityContext: {}

secret:
  p12: "Cg=="

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

networkpolicy:
  from:
    ingress: true
  to:
    dns: true
