apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  consolidation:
    enabled: true
  providerRef:
    name: default
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
      - on-demand
      - spot
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values:
      - "4"
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: kubernetes.io/os
      operator: In
      values:
      - linux
  limits:
    resources:
      cpu: 1000
